site_name: SinusBot Documentation
site_url: https://sinusbot.github.io/docs/
copyright: 'Copyright &copy; 2019 The SinusBot Team and Contributors.'
edit_uri: https://github.com/SinusBot/docs/edit/master/docs/
nav:
  - 'Introduction': 'index.md'
  - 'Installation':
    - 'Linux': 'installation/linux.md'
    - 'Windows': 'installation/windows.md'
    - 'Docker': 'installation/docker.md'
    - 'youtube-dl': 'youtube-dl.md'
    - 'Reverse Proxy':
      - 'NGINX': 'reverse-proxy/nginx.md'
      - 'Apache 2': 'reverse-proxy/apache2.md'
      - 'Common Adaptations': 'reverse-proxy/common-adaptations.md'
    - 'Increase TS Security Level': 'installation/increase-security-level.md'
  - 'FAQ':
    - 'General': 'faq/general.md'
    - 'Installation': 'faq/installation.md'
    - 'Features': 'faq/features.md'
  - 'What is new?': 'whatsnew.md'
  - 'Scripting': 'scripts.md'
  - 'Configuration': 'configuration.md'
  - 'Licenses': 'licenses.md'
  - 'Localization': 'locales.md'
  - 'Text-to-Speech': 'tts.md'
  - 'Speech Recognition': 'speechrecognition.md'
theme:
  name: 'material'
  font: false
  logo: 'logo.svg'
  favicon: 'https://sinusbot.github.io/favicon.ico'
  palette:
    primary: 'red'
    accent: 'red'
markdown_extensions: # see https://python-markdown.github.io/extensions/, https://facelessuser.github.io/pymdown-extensions/
  - codehilite
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.mark
  - toc:
      permalink: "\ue157"
extra_css:
  - extra.css
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://sinusbot.com
    - icon: fontawesome/brands/github
      link: https://github.com/SinusBot
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sinusbot
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/sinusbot
    - icon: fontawesome/solid/question
      link: https://forum.sinusbot.com
